### ISSUE TITLE
Feature Request: Reuse sounds

### ISSUE THREAD

**Issue by Lusito** [EvandroLG/ts-audio#15]
Scenario: I want to create a game capable of playing the same sound multiple times and possibily at the same time.

It would be good if I had a SoundBuffer fetching the data into memory and then a separate Audio class, which can be used to play that SoundBuffer without having to re-download for every new Audio instance.

**Comment by EvandroLG** [comment]
Hi @Lusito 

I don't know if it makes a lot of sense, because the browser already caches the downloaded file.
Considering that, what would be the befit?

**Comment by Zaynex** [comment]
Can Audio instance play twice or more ?
For example:
```
const audio = new Audio({
  file: './demo.mp3'
})

audio.play();

// after audio finish, I want resue it again
// and I call audio.play() in some cases	
audio.play();  // -> does it work?
```

**Comment by EvandroLG** [comment]
@Zaynex actually not and to be honest I was not aware of it. Good catch guys! :D
For now, we need to create another audio object.

I'll try to have time during this weekend and create a solution for this issue :D

Thanks guys

**Comment by EvandroLG** [comment]
@Zaynex I released yesterday a new version with a solution for your problem.
Let me know if it's working fine to you :)
