### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by bradwoods** [EvandroLG/ts-audio#26]
I'm getting a **window is not defined** when calling:
`
const audio = Audio({
        file: `myAudioFile`,
        volume: 1,
    });
`

Running in Next.JS environment. Has anyone seen this before?

**Comment by EvandroLG** [comment]
Hi @bradwoods 

I assume you are getting it because your code is running on the server. Does it make sense?
For solving it, you should check if your code is running on the client and then invoke `Audio`.

Let me know if it's a fine solution for your case :)

**Comment by bradwoods** [comment]
Hey mate, yep. I refactored so I'm defining a new Audio instance each time a sound plays. Doesn't look the best what does work. Do you see any problems doing this - 

```
export const sounds = {
    schema: () => {
        Audio({
            file: sputnik,
            volume: 0.1,
        }).play();
    },
    server: () => {
        Audio({
            file: ocean,
            volume: 0.2,
        }).play();
    },
    resolver: () => {
        Audio({
            file: space,
            volume: 0.2,
        }).play();
    },
    dataSource: () => {
        Audio({
            file: rocks,
            volume: 0.2,
        }).play();
    },
    client: () => {
        Audio({
            file: comms,
            volume: 0.1,
        }).play();
    },
};
```

**Comment by EvandroLG** [comment]
I don't have too much context about your code, but I would highlight that it is important not to create many objects in memory for performance reasons. Other than that, it seems fine to me :)

**Comment by EvandroLG** [comment]
Hi @bradwoods 
Any more question man or could we close this issue? :)

**Comment by bradwoods** [comment]
Sorry, yep. Close this issue. Thanks for the quick response!
