### ISSUE TITLE
Sound state

### ISSUE THREAD

**Issue by bradwoods** [EvandroLG/ts-audio#31]
Is there a way to automatically change the state of a sound from `running` after the sound has finished playing and `loop: false`?

**Comment by EvandroLG** [comment]
Hi @bradwoods 

You can change the sound state using `pause` or `stop` methods. Did I answer your question? :)

About the `loop`, you would like to have a method to change the `loop` state after initializing the `Audio` object, is it? 
If so, we don't have it yet, but it would relatively simple to implement it. I could release it still this week if it would help you :)

**Comment by bradwoods** [comment]
hey mate,

The scenario I was referring to was if I play an audio file that lasts 10 seconds (and I'm not looping it), after that 10 seconds, the sound state will be in the 'running' state, even though the sound has completed. Would it be useful to have this state automatically change to `stop` when a sound has been completed?

**Comment by EvandroLG** [comment]
It is a good point @bradwoods, thanks for bringing it up!
To be honest, I also would expect to see a different state after the audio finishes playing. However, it is the default state from the AudioContext API (https://developer.mozilla.org/en-US/docs/Web/API/BaseAudioContext/state) and at the moment we are not changing it. 

Maybe we could have different states than the ones provided by the AudioContext API, something like:
- ready
- playing
- paused
- stoped
- finished

Please let me know what you think of my suggestion and if I am missing any other relevant state :)

**Comment by bradwoods** [comment]
That makes sense to stay consistent with the AudioContext API. Those all make sense to me.

**Comment by EvandroLG** [comment]
For consistency with the original API, let's keep the state as they are today.
