### ISSUE TITLE
control audio with react context

### ISSUE THREAD

**Issue by phuc-dev17** [EvandroLG/ts-audio#40]
Hey there, my case is that I want to control audio from other components
Is there any events, methods that I can use to archive my goal?

**Comment by EvandroLG** [comment]
Hi @phuc-dev17 
Are u using Audio or Playlist? Anyway, for both we have events that should be useful for your case:
- https://github.com/EvandroLG/ts-audio/wiki/Audio:-Events
- https://github.com/EvandroLG/ts-audio/wiki/AudioPlaylist:-Events

Please, let me know in case u need new events :)
