### ISSUE TITLE
expose AudioContext as a read only property

### ISSUE THREAD

**Issue by zivni** [EvandroLG/ts-audio#41]
It will be helpful if you expose the underlining  AudioContext so we can use it for such things as an audio visualizer

**Comment by EvandroLG** [comment]
It's a good point! Thanks @zivni!
How would u like to get it? I think it would be also useful to export it from the AudioPlaylist, right?

**Comment by zivni** [comment]
As a read only  property.  Just like the state

**Comment by EvandroLG** [comment]
@zivni just released a new version of ts-audio adding `audioCtx` in both `Audio` and `AudioPlaylist`.
Thanks for your suggestion dude!
