### ISSUE TITLE
Feature request: implement getter/setter for current play time

### ISSUE THREAD

**Issue by MrLuit** [EvandroLG/ts-audio#44]
I really like the playlist feature of this library, but I would like to be able to get and update the current time position of the audio being played. This would allow React implementations to display the current play time and also allow users to scrub through audio files.

This feature could be implemented directly or you could give developers the ability to implement this functionality by exposing the audio context (https://github.com/EvandroLG/ts-audio/issues/41)

Helpful links:
- https://developer.mozilla.org/en-US/docs/Web/API/AudioBufferSourceNode/start
- https://developer.mozilla.org/en-US/docs/Web/API/BaseAudioContext/currentTime

**Comment by EvandroLG** [comment]
It's a very good suggestion, thanks @MrLuit 
In the next release, I will update the Audio component to expose the AudioContext, so I think it should be enough to implement more functionalities as the one you mentioned. WDYT? :)

**Comment by EvandroLG** [comment]
@MrLuit just released a new version of ts-audio adding `audioCtx` for both `Audio` and `AudioPlaylist`.
Thanks for your suggestion dude!

**Comment by N3koSempai** [comment]
Hello, @EvandroLG. What are the properties in audioCtx to obtain the current playback position and the maximum duration of the audio file? Do these properties exist?
