### ISSUE TITLE
Audio playback in ogg format is not supported

### ISSUE THREAD

**Issue by hairyf** [EvandroLG/ts-audio#52]

**Comment by EvandroLG** [comment]
Hey @hairyf  👋 
I just tested it and didn't find any problem. I pushed a code example here: https://github.com/EvandroLG/ts-audio/tree/dev/demo
Do you have a code example that I could check out? It would be nice to see the issue happening in your specific context

**Comment by hairyf** [comment]
Sorry, this seems to be a mistake in my judgment

I used it in vite and didn't notice that the import. meta. global function returned an object

```ts
const importPaths = import.meta.glob('../assets/audio/*.ogg', { eager: true })

importPaths[...].default
```

Thank you, this library is very stable!

I used it to create a bird demo

> https://github.com/hairyf/vue3-pixi-flappy-bird
