### ISSUE TITLE
I use this code on firefox

### ISSUE THREAD

**Issue by junhuanchen** [EvandroLG/ts-audio#9]
I use this code on firefox.

https://github.com/junhuanchen/webduino-module-azrue-speech/blob/79629695d6a87efba81287f566c0ce375ec09aff/audioJS.js#L150

https://github.com/junhuanchen/webduino-module-azrue-speech/blob/79629695d6a87efba81287f566c0ce375ec09aff/audioJS.js#L114

https://github.com/junhuanchen/webduino-module-azrue-speech/blob/79629695d6a87efba81287f566c0ce375ec09aff/audioJS.js#L99-L100

maybe need fix this.source.gain func.

**Comment by EvandroLG** [comment]
@junhuanchen Thank you. It should be working fine now.
I just released a new version of the library. Let me know if you encounter any other problems :)
